---
version: "3.8"
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_DATABASE: jwts
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - mysql_data:/var/lib/mysql
  upload-users:
    build:
      context: 
      dockerfile: Dockerfile
    restart: always
    environment:
      - spring.application.name=upload-users
      - spring.datasource.url=jdbc:mysql://mysql:3306/jwts
      - spring.datasource.username=root
      - spring.datasource.password=root
      - spring.jpa.show-sql=true
      - spring.jpa.hibernate.ddl-auto=update
      - spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
      - server.port=4321
    ports:
      - 4321:4321
volumes:
  mysql_data: null
